# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0004_auto_20170918_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='excerpt',
            field=models.TextField(blank=True, max_length=70, verbose_name='excerpt'),
        ),
    ]
