# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0005_product_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'public/upload/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_caption',
            field=models.TextField(blank=True, help_text="Image's caption.", verbose_name='caption'),
        ),
    ]
