# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0006_auto_20170918_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'uploads/product_catalog/%Y/%m/%d/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_caption',
            field=models.CharField(blank=True, help_text="Image's caption.", max_length=250, verbose_name='caption'),
        ),
    ]
