# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0008_auto_20170921_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Max length: 70 characters', max_length=70, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=[b'title', b'id'], unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='publicationproduct',
            name='end_publication',
            field=models.DateTimeField(blank=True, help_text='End date of publication.', null=True, verbose_name='end publication'),
        ),
        migrations.AlterField(
            model_name='publicationproduct',
            name='start_publication',
            field=models.DateTimeField(blank=True, help_text='Start date of publication.', null=True, verbose_name='start publication'),
        ),
        migrations.AlterField(
            model_name='publicationproduct',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'hidden'), (2, 'published')], db_index=True, default=2, verbose_name='status'),
        ),
    ]
